name: tablet_chords_dart
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  args: ^2.0.0
  planningcenter_api: ^1.1.1
  # planningcenter_api:
  #   path: /Users/Jeff/Development/@Dart/planningcenter_api
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_static: ^1.1.1
  shelf_web_socket: ^1.0.2
  web_socket_channel: ^2.2.0
  xml: ^6.1.0

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
